/**
 * Tests for getBoundsForCustomZeroPosition().
 *
 * The file is disabled (renamed to *.dis) & thus is not used during a build process;
 * remove the "dis" extension to use it locally in your VSCode devcontainer.
 */

import { expect, describe, it } from 'vitest';
import { getBoundsForCustomZeroPosition } from '../src/others';

const VARIANTS: any[] = [
  // zeroPos: undefined
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: undefined,
    invert: undefined,
    expected: '',
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0 (0.1)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0,
    invert: undefined,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0,
    invert: undefined,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0,
    invert: undefined,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0,
    invert: undefined,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0,
    invert: undefined,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0,
    invert: undefined,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0,
    invert: undefined,
    expected: [-1000*9999, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0,
    invert: undefined,
    expected: [-10*9999, 10],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0,
    invert: undefined,
    expected: [-100*9999, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 1 (0.2)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 1,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 1,
    invert: undefined,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 1,
    invert: undefined,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 1,
    invert: undefined,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 1,
    invert: undefined,
    expected: [-100, 100*9999],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.5 (1)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-1000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.5,
    invert: undefined,
    expected: [-100, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.4 (1.1)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-150, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-150, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-150, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-1500, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.4,
    invert: undefined,
    expected: [-150, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.25 (1.2)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-300, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-300, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-300, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-100, 100/3],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-100, 100/3],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-100, 100/3],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-3000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-100, 100/3],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.25,
    invert: undefined,
    expected: [-300, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.1 (1.3)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-900, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-900, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-900, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-9000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.1,
    invert: undefined,
    expected: [-900, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.05 (1.4)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-1900, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-1900, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-1900, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-19000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-190, 10],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.05,
    invert: undefined,
    expected: [-1900, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.6 (2.1)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100, 150],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100, 150],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100, 150],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-1000*2/3, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100, 150],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.6,
    invert: undefined,
    expected: [-100, 150],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.9 (2.2)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100, 900],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100, 900],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100, 900],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-1000/9, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100, 900],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.9,
    invert: undefined,
    expected: [-100, 900],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.95 (2.3)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.95,
    invert: undefined,
    expected: [-100, 1900],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: undefined (inverted)
  {
    description: 'both bounds = 0 (inverted)',
    bounds: [0, 0],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive (inverted)',
    bounds: [10, 100],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive (|L| = |U|) (inverted)',
    bounds: [100, 100],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive (L = 0) (inverted)',
    bounds: [0, 100],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds negative (inverted)',
    bounds: [-100, -10],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds negative (|L| = |U|) (inverted)',
    bounds: [-100, -100],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds negative (U = 0) (inverted)',
    bounds: [-100, 0],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| < |U|) (inverted)',
    bounds: [-100, 1000],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| > |U|) (inverted)',
    bounds: [-100, 10],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  {
    description: 'bounds positive & negative (|L| = |U|) (inverted)',
    bounds: [-100, 100],
    zeroPos: undefined,
    invert: true,
    expected: '',
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.5 (1) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.5,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.5,
    invert: true,
    expected: [-1000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.5,
    invert: true,
    expected: [-100, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.4 (1.1) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.4,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.4,
    invert: true,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.4,
    invert: true,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.4,
    invert: true,
    expected: [-100*2/3, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.4,
    invert: true,
    expected: [-100, 150],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.4,
    invert: true,
    expected: [-100, 150],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.4,
    invert: true,
    expected: [-100, 150],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.4,
    invert: true,
    expected: [-1000*2/3, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.4,
    invert: true,
    expected: [-100, 150],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.4,
    invert: true,
    expected: [-100, 150],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.25 (1.2) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.25,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.25,
    invert: true,
    expected: [-100/3, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.25,
    invert: true,
    expected: [-100/3, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.25,
    invert: true,
    expected: [-100/3, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.25,
    invert: true,
    expected: [-100, 300],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.25,
    invert: true,
    expected: [-100, 300],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.25,
    invert: true,
    expected: [-100, 300],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.25,
    invert: true,
    expected: [-1000/3, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.25,
    invert: true,
    expected: [-100, 300],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.25,
    invert: true,
    expected: [-100, 300],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.1 (1.3) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.1,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.1,
    invert: true,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.1,
    invert: true,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.1,
    invert: true,
    expected: [-100/9, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.1,
    invert: true,
    expected: [-100, 900],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.1,
    invert: true,
    expected: [-100, 900],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.1,
    invert: true,
    expected: [-100, 900],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.1,
    invert: true,
    expected: [-1000/9, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.1,
    invert: true,
    expected: [-100, 900],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.1,
    invert: true,
    expected: [-100, 900],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.05 (1.4) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.05,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.05,
    invert: true,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.05,
    invert: true,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.05,
    invert: true,
    expected: [-100/19, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.05,
    invert: true,
    expected: [-100, 1900],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.6 (2.1) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.6,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.6,
    invert: true,
    expected: [-150, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.6,
    invert: true,
    expected: [-150, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.6,
    invert: true,
    expected: [-150, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.6,
    invert: true,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.6,
    invert: true,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.6,
    invert: true,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.6,
    invert: true,
    expected: [-1500, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.6,
    invert: true,
    expected: [-100, 100*2/3],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.6,
    invert: true,
    expected: [-150, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.9 (2.2) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.9,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.9,
    invert: true,
    expected: [-900, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.9,
    invert: true,
    expected: [-900, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.9,
    invert: true,
    expected: [-900, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.9,
    invert: true,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.9,
    invert: true,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.9,
    invert: true,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.9,
    invert: true,
    expected: [-9000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.9,
    invert: true,
    expected: [-100, 100/9],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.9,
    invert: true,
    expected: [-900, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0.95 (2.3) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0.95,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0.95,
    invert: true,
    expected: [-1900, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0.95,
    invert: true,
    expected: [-1900, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0.95,
    invert: true,
    expected: [-1900, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0.95,
    invert: true,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0.95,
    invert: true,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0.95,
    invert: true,
    expected: [-100, 100/19],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0.95,
    invert: true,
    expected: [-19000, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0.95,
    invert: true,
    expected: [-190, 10],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0.95,
    invert: true,
    expected: [-1900, 100],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 0 (0.1) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 0,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 0,
    invert: true,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 0,
    invert: true,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 0,
    invert: true,
    expected: [-100/9999, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 0,
    invert: true,
    expected: [-100, 100*9999],
  },
  ///////////////////////////////////////////////////////////////////////////////////
  // zeroPos: 1 (0.2) (inverted)
  {
    description: 'both bounds = 0',
    bounds: [0, 0],
    zeroPos: 1,
    invert: true,
    expected: [-Number.EPSILON, Number.EPSILON],
  },
  {
    description: 'bounds positive',
    bounds: [10, 100],
    zeroPos: 1,
    invert: true,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds positive (|L| = |U|)',
    bounds: [100, 100],
    zeroPos: 1,
    invert: true,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds positive (L = 0)',
    bounds: [0, 100],
    zeroPos: 1,
    invert: true,
    expected: [-100*9999, 100],
  },
  {
    description: 'bounds negative',
    bounds: [-100, -10],
    zeroPos: 1,
    invert: true,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds negative (|L| = |U|)',
    bounds: [-100, -100],
    zeroPos: 1,
    invert: true,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds negative (U = 0)',
    bounds: [-100, 0],
    zeroPos: 1,
    invert: true,
    expected: [-100, 100/9999],
  },
  {
    description: 'bounds positive & negative (|L| < |U|)',
    bounds: [-100, 1000],
    zeroPos: 1,
    invert: true,
    expected: [-1000*9999, 1000],
  },
  {
    description: 'bounds positive & negative (|L| > |U|)',
    bounds: [-100, 10],
    zeroPos: 1,
    invert: true,
    expected: [-10*9999, 10],
  },
  {
    description: 'bounds positive & negative (|L| = |U|)',
    bounds: [-100, 100],
    zeroPos: 1,
    invert: true,
    expected: [-100*9999, 100],
  },
];

describe("getBoundsForCustomZeroPosition", () => {
  VARIANTS.forEach((variant) => {
    it(`getBoundsForCustomZeroPosition: check [${JSON.stringify(variant)}], ${variant.description}`, () => {
      const result = getBoundsForCustomZeroPosition(
        variant.bounds,
        variant.zeroPos,
        variant.invert,
      );
      let expected_0;
      let expected_1;
      if (variant.zeroPos === undefined) {
        expected_0 = variant.bounds[0];
        expected_1 = variant.bounds[1];
      } else {
        expected_0 = variant.expected[0];
        expected_1 = variant.expected[1];
      }
      expect(result[0]).toBeCloseTo(expected_0, 4);
      expect(result[1]).toBeCloseTo(expected_1, 4);
    });
  });

});
