views:
  - title: Main
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.humidity
      - type: custom:mini-graph-card
        entities:
          - sensor.temperature
      - type: custom:mini-graph-card
        entities:
          - sensor.pressure
        show:
          extrema: true
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 60
        entities:
          - entity: sensor.random0_100
            name: Random 0 - 100
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 20
        lower_bound: 0
        upper_bound: 100
        # agregate_fun: median
        entities:
          - entity: sensor.random0_100
            name: Random MEDIAN
            aggregate_func: median
          - entity: sensor.random0_100
            name: Random AVG
